### ISSUE TITLE
File Permission Issue with Console Commands

### ISSUE THREAD

**Issue by chaseconey** [RicLeP/laravel-storyblok#16]
## Overview

It appears that there is an issue when using the console commands that are using the `replace` method on files where it will actually update file permissions unnecessarily.

## Steps to Reproduce

1. Create a component in Storyblok
2. Create class representation for said component `php artisan ls:block <component>`
3. Add a new field to the component
4. Run `php artisan ls:sync`

## Expected Outcome

The new field will show up as a property for that block's class. File permissions should remain 644 (rw, r, r).

## Actual Outcome

The new field will show up as a property for that block's class. File permissions are updated to 755 (rwx, rx, rx).

**Comment by RicLeP** [comment]
Thanks, this is fixed in 2.5.20. Laravel’s Filessystem `replace()` method seems to change a file’s permissions, not exactly sure what’s happening under the hood.
