### ISSUE TITLE
Dealing with pagination

### ISSUE THREAD

**Issue by kbrookes** [RicLeP/laravel-storyblok#22]
Hi @RicLeP, I was wondering how you'd deal with paginating through the StoryBlok API when there's more than 100 articles in a 'collection'. 

E.G. my client has a blog with several hundred articles - I couldn't see a process for iterating through all of the blog posts - just the first 100.

**Comment by RicLeP** [comment]
Hello,

For this I’d use a `Folder` (https://ls.sirric.co.uk/docs/2.9/folders) which allows you to grab multiple stories in one go, it basically wraps this request (https://www.storyblok.com/docs/api/content-delivery#core-resources/stories/retrieve-multiple-stories).


```php
<?php
// Folder definition

namespace App\Storyblok\Folders;


use App\Storyblok\Folder;

class Speakers extends Folder
{
    protected $slug = 'speakers';
    protected $sortBy = 'content.published:desc';

    public function __construct()
    {

    }
}

```


I like using View Components but you could do exactly the same in a controller. Here I create a new `SpeakerList` instance and pass in the pagination (https://www.storyblok.com/docs/api/content-delivery#topics/pagination) details in the settings.

```php
<?php

namespace App\View\Components;

use App\Storyblok\Folders\Speakers as SpeakerList;
use Illuminate\Http\Request;
use Illuminate\View\Component;

class Speakers extends Component
{

    public $speakers;

    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct(Request $request)
    {
	    $settings = [
		    'per_page' => 20,
		    'page' => $request->get('page') ?? 1
	    ];

        $speakers = new SpeakerList();
        $speakers->settings($settings);

        $this->speakers = $speakers->read();
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('components.speakers');
    }
}
```


In the Blade for the View Component I am simply adding buttons that increment/decrement the page.

```php
@if ($speakersByYear->isNotEmpty())
	<a href="?page={{ !request()->has('page') ? 2 : request()->get('page') + 1 }}">Previous</a>
@endif

@if (request()->get('page') > 1)
	<a href="?page={{ request()->get('page') - 1 }}">Next</a>
@endif
```

The Blade section is pretty crude in my example. Storyblok’s API does return additional data about the `Stories` response that the package doesn’t pick up, such as the total number of items. You can see everything returned by using their API directly (this example doesn’t cache the results so you’d want to implement that so save hammering the API).

```
$storyblokClient = resolve('Storyblok\Client');

$storyblokClient =  $storyblokClient->getStories(array_merge([
	'is_startpage' => false,
	'sort_by' => 'some-sort',
	'starts_with' => 'some-slug',
	'page' => 1,
	'per_page' => 20,
], $this->settings));

dd($storyblokClient->getHeaders(), $storyblokClient->getBody());
```

---

I think I’ll be adding better pagination to the package very soon.

**Comment by kbrookes** [comment]
Thank you @RicLeP ! That helps a lot.

**Comment by RicLeP** [comment]
Version 2.10.1 supports paginating folders: https://ls.sirric.co.uk/docs/2.10/folders#pagination
