### ISSUE TITLE
Question about serializing blocks

### ISSUE THREAD

**Issue by chaseconey** [RicLeP/laravel-storyblok#24]
### Question

Hey there 👋 .

This is more of a question than a feature request or bug ticket.

Let's say you have a block that you are going to serialize (via json_encode or the like). This package uses the magic `__get()` function to get attributes out of the private `$fields` array behind the scenes, so the JSON encoded object only has a few public properties (resolve relations and whatnot).

Is there a native way to get the full class serialized with all of the Storyblok attributes included? If there isn't, would that be something you want this package to handle?

### Background

A lot of times we are using Storyblok to render our data, but then there are some frontend manipulations that we want to do as well. To accomplish our goals, sometimes we need to encode the Storyblok object into javascript to be used on the client.

### Example

If I use the laravel `@json` directive on any component, the output will look similar to this:

```
{"_autoResolveRelations":false,"_resolveRelations":[],"_filterRelations":true,"_componentPath":["page","page","full-section","button"]}
```

But if I `@dd` that same instance, I get something like this:

```
App\Storyblok\Blocks\Button {[#1588 ▼]
  +_autoResolveRelations: false
  +_resolveRelations: []
  +_filterRelations: true
  +_componentPath: array:4 [[▶]()]
  #_casts: []
  -_fields: Illuminate\Support\Collection {[#1589 ▼]()
    #items: array:15 [[▼]()
      "url" => Riclep\Storyblok\Fields\UrlLink {[#1592 ▶]()}
      "size" => "normal"
      "text" => "Rawr"
    ]
    #escapeWhenCastingToString: false
    // other attributes
  }
}
```

Notice that the component has data like `size` and `text` in it, but it doesn't show up in the serialized instance.

**Comment by RicLeP** [comment]
Hi @chaseconey 

If I’m reading this correctly you basically want to get a JSON representation of the Block? There are couple of variations to that:

- JSON just like Storyblok provides
- JSON of content fields (potentially with mutators?)
- JSON of the block, with the package specific data (or sub set of) and the content

It’s definitely something I’ve thought about, being able to send JSON to the frontend more easily. There isn’t any way to handle any of the above yet.

Blocks could have a `toJSON` method - and would this attach meta data? Maybe mapping the fields you want in the JSON.

Or something like [Laravel’s API Resources](https://laravel.com/docs/9.x/eloquent-resources)? I’ve not used them much so am not that familiar with their pros and cons.

There could also be a benefit to being able to stop parsing the nested blocks and keeping some as JSON. Maybe a nested block doesn’t need to be transformed into a class and simply becomes a JSON or array ‘field’ on the parent?

Sorry, not really answering anything for you here, but is this the kind of thoughts you were having?

**Comment by RicLeP** [comment]
Hi @chaseconey, do you happen to know exactly what Laravel is doing under the hood with calling `@json'? I can’t see where this directive defined in the framework. I’ve been playing with a couple of ideas but need to know what `@json` does.

**Comment by czuniga9** [comment]
@RicLeP looking at a view generated in `storage/framework/views/`, I can see that `@json($foo)` generates `<?php echo json_encode($foo, 15, 512) ?>;`.

The 15 being these flags: `JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT`.

**Comment by RicLeP** [comment]
Thanks @czuniga9 ! I didn’t think to look it the compiled view 😅

In 2.10.6 `Block` now implements `JsonSerializable`, see: https://www.php.net/manual/en/class.jsonserializable.php

By default it uses `$this->content()`. If you need something more bespoke then you’ll need to override the `jsonSerialize()` method on your `Block`.

I did something similar recently before implementing `JsonSerializable` which should be easy to migrate to the new style.

```php
class Nav extends BaseBlock
{
    public function toArray() {
	return $this->content()->transform(function ($item) {
		return $item->transform(function ($item) {
			return $item->toArray();
		});
	})->first();
    }
}
```

```php
class NavDropdown extends BaseBlock
{
	public function toArray() {
		$dropDown =  $this->content()->transform(function ($item) {
			if (is_string($item)) {
				return $item;
			}

			return $item->transform(function ($item) {
				return $item->toArray();
			});
		});

		$dropDown['isOpen'] = false;

		return $dropDown;
	}
}
```

```php
class NavLink extends BaseBlock
{
	public function toArray() {
		return $this->content()->transform(function ($item) {
			return is_string($item) ? $item : rtrim((string) $item, '/');
		});
	}
}
```

With the structure:

![image](https://user-images.githubusercontent.com/19726976/159908088-6c60f001-9ea8-411d-84d0-75ee86734e07.png)
