### ISSUE TITLE
Detecting broken images to prevent calling transform()

### ISSUE THREAD

**Issue by kbrookes** [RicLeP/laravel-storyblok#26]
A bit of an edge case here, but I've got a StoryBlok instance where we imported thousands of articles into the system, and we have a ton of broken images.

The client's gradually going through and fixing them, but we've gone live anyway - so there's a lot of older pages that just error out when we use `$image->transform()`.

My current method of detecting if an image exists or not is to do a check on `$story->image->filename`.

However with broken images imported into Storyblok, there's still a filename (which is helping my client to figure out which images need to be added back in).

I could probably do a check on the `$image->copyright` or `$image->alt` fields - these are null on broken images, and if not utilised are empty.

But I thought it might be a better option to be able to check the transformer for the extension type - which will return null on these images.

As I said, very much an edge case, but I'd be interested to hear your thoughts on a solve.

**Comment by RicLeP** [comment]
Hi @kbrookes, sorry I missed this.

All Assets, which Image extends, have a `hasFile()` method

```
@if ($block->image->hasFile())
	<img src="{{ $block->image->transform()->resize(600, 300, 'smart') }}" alt>
@else
	// handle broken images...
@endif
```


If you’re using PHP 8+ then you can use [the null safe operator](https://stitcher.io/blog/php-8-nullsafe-operator) on the image which is a little more robust.

```
@if ($block->image?->hasFile())
	<img src="{{ $block->image->transform()->resize(600, 300, 'smart') }}" alt>
@endif
```

**Comment by kbrookes** [comment]
Thank you! That's really great to know.
