### ISSUE TITLE
Enable (rendering of) inline components within the RichText field

### ISSUE THREAD

**Issue by papoms** [RicLeP/laravel-storyblok#3]
Hey, again thanks for the nice package!

Storyblok allows to insert components within the RichText field [1]. But from what i understood the provided storyblok/richtext-resolver for PHP does not handle them. Anyways, i needed to render inline components and came up with the following code. Maybe its a common enough use-case to be added to the core of this package.

I found no way to overwrite the existing RichText Field Class, so i added a Custom Field and named it accordingly in Storyblok. Maybe it would be nice if one could also overwrite the built-in fields to apply changes globally based on the field type vs the field name.

```php
<?php

namespace App\Storyblok\Fields;

use Riclep\Storyblok\Fields\RichText as BaseRichText;
use Storyblok\RichtextRender\Resolver;
use Riclep\Storyblok\Block;

class Richtextfield extends BaseRichText
{
	/**
	 * Converts the data to HTML when printed
	 *
	 * @return string
	 */
	public function __toString()
	{
        $richtextResolver = new Resolver();

        $out = "";
        // Loop through all nodes from the RichText Field
        // Either Render them normally
        // Or if type is 'blok' create a block an add the rendered content to ouput
        foreach ($this->content['content'] as $node) {
            if ($node['type'] == 'blok' && isset($node['attrs']['body']) && is_array($node['attrs']['body'])){
                foreach ($node['attrs']['body'] as $blockContent) {
                    $block = new Block($blockContent, $this->block()->parent());
                    $out .= $block->render();
                }
            } else {
                $out .= $richtextResolver->render(["content" => [$node]]);
            }
        }
        return $out;
        // Original
		// return $richtextResolver->render($this->content);
	}
}
```

[1] https://www.storyblok.com/docs/richtext-field#components-inside-the-richtext-field

**Comment by papoms** [comment]
Updated it to also respect Custom Block Classes instead of using the default Block Class.

```php
<?php

namespace App\Storyblok\Fields;

use Riclep\Storyblok\Fields\RichText as BaseRichText;
use Storyblok\RichtextRender\Resolver;
use Riclep\Storyblok\Block;
use Riclep\Storyblok\Traits\HasChildClasses;

class Richtextfield extends BaseRichText
{
    use HasChildClasses;
	/**
	 * Converts the data to HTML when printed
	 *
	 * @return string
	 */
	public function __toString()
	{
        $richtextResolver = new Resolver();

        $out = "";
        // Loop through all nodes from the RichText Field
        // If the node type is 'blok' it is an inline component -> render it as block
        // else just use the richtextResolver as normally
        foreach ($this->content['content'] as $node) {

            if ($node['type'] == 'blok' && isset($node['attrs']['body']) && is_array($node['attrs']['body'])){
                foreach ($node['attrs']['body'] as $blockContent) {
                    $class = $this->getChildClassName('Block', $blockContent['component']);
                    $block = new $class($blockContent, $this->block()->parent());
                    $out .= $block->render();
                }
            } else {
                $out .= $richtextResolver->render(["content" => [$node]]);
            }
        }
        return $out;
	}
}

```

**Comment by RicLeP** [comment]
This looks interesting. I’ve not tried using components in rich-text fields before and worried clients will go crazy with the editing power! Closing this ticket but will look to implement it as it is on my to-do list. Thank you.

**Comment by papoms** [comment]
> clients will go crazy with the editing power
Thats a valid point, had a good laugh ;-)
You can disable it within Storyblok.

**Comment by papoms** [comment]
We are using it on a food blog / Recipe App. 

The Blog Authors can include lists of Recipes within the article. Using the Rich-Text Fields allows to do so without splitting up the content in multiple richtext fields like

RichText
RecipeList
RichText
RecipeList

I also found it handy for more advanced control of inserting Images. The built-in method does not really support placement and size options. So i've created an ImageBlock that can now be placed directly within the Richtext Field.

**Comment by RicLeP** [comment]
Inserting images is a really good idea. I will need to explore it more as until now I’ve made a containing Block that could take different child blocks (text, quote, image etc.) but what you suggested does sound interesting.

I’d love to see the site you’re working on when it’s ready

**Comment by RicLeP** [comment]
Thanks for the code @papoms. I’ve tweaked it a bit to process the rich-text field’s content before the `__toString` method. It creates a `content` key in the field with a collection of all the HTML and Blocks. This way it can be manipulated further before rending in Blade. The `toString` method them loops over the `content` outputting HTML.

Do you have any thoughts on this as I’ve not used inline components much.

![image](https://user-images.githubusercontent.com/19726976/105380375-b5d29200-5c05-11eb-956a-bdbcbf12cb8d.png)

(Probably shouldn’t have closed the ticket yet either. I am new to maintaining open source!)

**Comment by RicLeP** [comment]
@papoms just pushed version 2.5 live with inline rendering. Thanks for the help with this.

**Comment by papoms** [comment]
Thanks for the update! I will look into it on sunday
